# from django.db import models

# # Create your models here.
# class data(models.Model):

#     CallCallConnectionId                                = models.CharField(max_length = 300, default="")
#     CallCallConnectionTime                              = models.CharField(max_length = 300, default="")
#     CallTimeToConnectInSeconds                          = models.CharField(max_length = 300, default="")
#     CallCallCompletedTime                               = models.CharField(max_length = 300, default="")
#     CallCallLengthInSeconds                             = models.CharField(max_length = 300, default="")
#     CallConnectionLengthInSeconds                       = models.CharField(max_length = 300, default="")
#     CallIsConversion                                    = models.CharField(max_length = 300, default="")
#     CallConversionAmount                                = models.CharField(max_length = 300, default="")
#     CallCallCost                                        = models.CharField(max_length = 300, default="")
#     CallProfit                                          = models.CharField(max_length = 300, default="")
#     CallLastDialTime                                    = models.CharField(max_length = 300, default="")
#     CallTimeToCallInSeconds                             = models.CharField(max_length = 300, default="")
#     CallCallDateTime                                    = models.CharField(max_length = 300, default="")
#     CallInboundCallId                                   = models.CharField(max_length = 300, default="")
#     CallInboundPhoneNumber                              = models.CharField(max_length = 300, default="")
#     CallProviderCallId                                  = models.CharField(max_length = 300, default="")
#     CallConversionPayout                                = models.CharField(max_length = 300, default="")
#     CallFromImpression                                  = models.CharField(max_length = 300, default="")
#     CallAccountId                                       = models.CharField(max_length = 300, default="")
#     CallNumberPoolId                                    = models.CharField(max_length = 300, default="")
#     CallNumberPoolName                                  = models.CharField(max_length = 300, default="")
#     CallAffiliateName                                   = models.CharField(max_length = 300, default="")
#     CallAffiliateId                                     = models.CharField(max_length = 300, default="")
#     CallAffiliateSubId                                  = models.CharField(max_length = 300, default="")
#     CallToken                                           = models.CharField(max_length = 300, default="")
#     CallImpressionDateTime                              = models.CharField(max_length = 300, default="")
#     CallIsPoolHit                                       = models.CharField(max_length = 300, default="")
#     CallRTBBidId                                        = models.CharField(max_length = 300, default="")
#     ConnectedTargetId                                   = models.CharField(max_length = 300, default="")
#     ConnectedTargetTargetGroupId                        = models.CharField(max_length = 300, default="")
#     ConnectedTargetIsHighRateTarget                     = models.CharField(max_length = 300, default="")
#     ConnectedTargetRingbaNumberId                       = models.CharField(max_length = 300, default="")
#     ConnectedTarget                                     = models.CharField(max_length = 300, default="")
#     ConnectedTargetTargetCallIncrement                  = models.CharField(max_length = 300, default="")
#     ConnectedTargetSearchNumer                          = models.CharField(max_length = 300, default="")
#     ConnectedTargetCapsMigrated                         = models.CharField(max_length = 300, default="")
#     ConnectedTargetIsCriteriaInverted                   = models.CharField(max_length = 300, default="")
#     ConnectedTargetBlockRecordings                      = models.CharField(max_length = 300, default="")
#     ConnectedTargetName                                 = models.CharField(max_length = 300, default="")
#     ConnectedTargetVersion                              = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroupId                              = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroupIsSimalDial                     = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroupDisableTargets                  = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroupIsCriteriaInverted              = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroupBlockRecordings                 = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroupName                            = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroup_Name                           = models.CharField(max_length = 300, default="")
#     ConnectedTargetGroup_Version                        = models.CharField(max_length = 300, default="")
#     tagCampaignId                                       = models.CharField(max_length = 300, default="")
#     CampaignUserCampaignId                              = models.CharField(max_length = 300, default="")
#     CampaignNumberDisplayFormat                         = models.CharField(max_length = 300, default="")
#     CampaignCountryCode                                 = models.CharField(max_length = 300, default="")
#     CampaignOfferId                                     = models.CharField(max_length = 300, default="")
#     CampaignOfferDraftId                                = models.CharField(max_length = 300, default="")
#     CampaignEvalAnonymDuplication                       = models.CharField(max_length = 300, default="")
#     CampaignPayoutDupesGlobal                           = models.CharField(max_length = 300, default="")
#     CampaignCampaignType                                = models.CharField(max_length = 300, default="")
#     CampaignFilterCallsThroughTCPAShield                = models.CharField(max_length = 300, default="")
#     CampaignPlayTCPAWarningMessage                      = models.CharField(max_length = 300, default="")
#     CampaignShakenStirAllowedAttestations               = models.CharField(max_length = 300, default="")
#     tagCampaignName                                     = models.CharField(max_length = 300, default="")
#     CampaignVersion                                     = models.CharField(max_length = 300, default="")
#     tag_CampaignTrackingId                              = models.CharField(max_length = 300, default="")
#     tagFacebookURLParametersURLParamters                = models.CharField(max_length = 300, default="")
#     bidid                                               = models.CharField(max_length = 300, default="")
#     tagPlacementInfoPlacementId                         = models.CharField(max_length = 300, default="")
#     tagPlacementInfoLandingPageId                       = models.CharField(max_length = 300, default="")
#     tagPlacementInfoLandingPageVersion                  = models.CharField(max_length = 300, default="")
#     tagPlacementInfoNumberPoolId                        = models.CharField(max_length = 300, default="")
#     tagPlacementInfoNumberPoolName                      = models.CharField(max_length = 300, default="")
#     tagPlacementInfoSearchTerm                          = models.CharField(max_length = 300, default="")
#     tagPlacementInfoSearchKeyWord                       = models.CharField(max_length = 300, default="")
#     tagTimeUTCHour                                      = models.CharField(max_length = 300, default="")
#     tagTimeUTCMinute                                    = models.CharField(max_length = 300, default="")
#     tagTimeUTCSecond                                    = models.CharField(max_length = 300, default="")
#     tagTimeHour                                         = models.CharField(max_length = 300, default="")
#     tagTimeMinute                                       = models.CharField(max_length = 300, default="")
#     tagTimeSecond                                       = models.CharField(max_length = 300, default="")
#     tagDateUTCWeekDay                                   = models.CharField(max_length = 300, default="")
#     tagDateUTCDay                                       = models.CharField(max_length = 300, default="")
#     tagDateUTCMonth                                     = models.CharField(max_length = 300, default="")
#     tagDateUTCYear                                      = models.CharField(max_length = 300, default="")
#     tagDateUTCDate                                      = models.CharField(max_length = 300, default="")
#     tagDateISODate                                      = models.CharField(max_length = 300, default="")
#     tagDateWeekDay                                      = models.CharField(max_length = 300, default="")
#     tagDateDay                                          = models.CharField(max_length = 300, default="")
#     tagDateMonth                                        = models.CharField(max_length = 300, default="")
#     tagDateYear                                         = models.CharField(max_length = 300, default="")
#     tagDateTimeZone                                     = models.CharField(max_length = 300, default="")
#     tagDateDate                                         = models.CharField(max_length = 300, default="")
#     # tagPublisherName                                    = models.CharField(max_length = 300, default="")
#     # tagPublisherCompany                                 = models.CharField(max_length = 300, default="")
#     # tagPublisherId                                      = models.CharField(max_length = 300, default="")
#     # tagPublisherSubId                                   = models.CharField(max_length = 300, default="")
#     # tagPublisherReplacementNumber                       = models.CharField(max_length = 300, default="")
#     # tagInboundNumberNumber                              = models.CharField(max_length = 300, default="")
#     # tagInboundNumberNumberNoPlus                        = models.CharField(max_length = 300, default="")
#     # tagInboundNumberNumberE164                          = models.CharField(max_length = 300, default="")
#     # tagInboundNumberCountryCode                         = models.CharField(max_length = 300, default="")
#     # tagInboundNumberCountryDigits                       = models.CharField(max_length = 300, default="")
#     # tagInboundNumberAreaCode                            = models.CharField(max_length = 300, default="")
#     # tagInboundNumberIsPhoneNumberValid                  = models.CharField(max_length = 300, default="")
#     # tagInboundNumberPrefix                              = models.CharField(max_length = 300, default="")
#     # tagInboundNumberSuffix                              = models.CharField(max_length = 300, default="")
#     # tagInboundNumberShakenStirValidated                 = models.CharField(max_length = 300, default="")
#     # tagInboundNumberShakenStirAttestation               = models.CharField(max_length = 300, default="")
#     # tagInboundNumberRegion                              = models.CharField(max_length = 300, default="")
#     # tagInboundNumberState                               = models.CharField(max_length = 300, default="")
#     # tagInboundNumberProvince                            = models.CharField(max_length = 300, default="")
#     # tagInboundNumberProvinceCode                        = models.CharField(max_length = 300, default="")
#     # tagInboundNumberNumberType                          = models.CharField(max_length = 300, default="")
#     # tagInboundNumberLocationType                        = models.CharField(max_length = 300, default="")
#     # tagInboundNumberRecordFound                         = models.CharField(max_length = 300, default="")
#     # tagInboundNumberRecordUpdated                       = models.CharField(max_length = 300, default="")
#     # tagInboundNumberTelco                               = models.CharField(max_length = 300, default="")
#     # tagInboundNumberConfidence                          = models.CharField(max_length = 300, default="")
#     # tagInboundNumberDirectoryAssistance                 = models.CharField(max_length = 300, default="")
#     # tagInboundNumberPhoneMatchCategory                  = models.CharField(max_length = 300, default="")
#     # tagInboundNumberIsPrepaid                           = models.CharField(max_length = 300, default="")
#     # tagInboundNumberPhoneMatchRecordType                = models.CharField(max_length = 300, default="")
#     # tagDialedNumberNumber                               = models.CharField(max_length = 300, default="")
#     # tagDialedNumberName                                 = models.CharField(max_length = 300, default="")
#     # tagCallLengthTotal                                  = models.CharField(max_length = 300, default="")
#     # tagCallLengthFromConnect                            = models.CharField(max_length = 300, default="")
#     # tagCallLengthFromDial                               = models.CharField(max_length = 300, default="")
#     # tagCallInfoIsDuplicate                              = models.CharField(max_length = 300, default="")
#     # tagTargetName                                       = models.CharField(max_length = 300, default="")
#     # tagTargetId                                         = models.CharField(max_length = 300, default="")
#     # tagTargetSubId                                      = models.CharField(max_length = 300, default="")
#     # tagBuyerId                                          = models.CharField(max_length = 300, default="")
#     # tagBuyerName                                        = models.CharField(max_length = 300, default="")
#     # tagBuyerSubId                                       = models.CharField(max_length = 300, default="")
#     # tagIvrId                                            = models.CharField(max_length = 300, default="")
#     # tagIvrName                                          = models.CharField(max_length = 300, default="")
#     # tagEndCallEndCallSource                             = models.CharField(max_length = 300, default="")
#     # tagRecordingRecordingUrl                            = models.CharField(max_length = 300, default="")
#     # tagGeoCountry                                       = models.CharField(max_length = 300, default="")
#     # tagGeoCountryCode                                   = models.CharField(max_length = 300, default="")
#     # tagGeoSubDivision                                   = models.CharField(max_length = 300, default="")
#     # tagGeoSubDivisionCode                               = models.CharField(max_length = 300, default="")
#     # tagGeoCity                                          = models.CharField(max_length = 300, default="")
#     # tagGeoZipCode                                       = models.CharField(max_length = 300, default="")
#     # tagGeoLatitude                                      = models.CharField(max_length = 300, default="")
#     # tagTechnologyIsMobile                               = models.CharField(max_length = 300, default="")
#     # tagTechnologyUserAgentString                        = models.CharField(max_length = 300, default="")
#     # tagTechnologyOS                                     = models.CharField(max_length = 300, default="")
#     # tagTechnologyOSVersion                              = models.CharField(max_length = 300, default="")
#     # tagTechnologyBrowser                                = models.CharField(max_length = 300, default="")
#     # tagTechnologyBrowserVersion                         = models.CharField(max_length = 300, default="")
#     # tagTechnologyIPAddress                              = models.CharField(max_length = 300, default="")
#     # tagConnectionInfoISP                                = models.CharField(max_length = 300, default="")
#     # tagConnectionInfoOrganizationName                   = models.CharField(max_length = 300, default="")
#     # tagConnectionInfoAutonomousName                     = models.CharField(max_length = 300, default="")
#     # tagConnectionInfoAutonomousSystemNumber             = models.CharField(max_length = 300, default="")
#     # tagRequestInfoReferrerPage                          = models.CharField(max_length = 300, default="")
#     # tagRequestInfoLandingPageUrl                        = models.CharField(max_length = 300, default="")
#     # tagScreenInfoWidth                                  = models.CharField(max_length = 300, default="")
#     # tagScreenInfoHeight                                 = models.CharField(max_length = 300, default="")
#     # tagScreenInfoPixelDensity                           = models.CharField(max_length = 300, default="")
#     # tagScreenInfoColorDepth                             = models.CharField(max_length = 300, default="")
#     # tagIdentityFirstName                                = models.CharField(max_length = 300, default="")
#     # tagIdentityLastName                                 = models.CharField(max_length = 300, default="")
#     # tagIdentityMiddleName                               = models.CharField(max_length = 300, default="")
#     # tagIdentityBusinessName                             = models.CharField(max_length = 300, default="")
#     # tagAddressStreetNumber                              = models.CharField(max_length = 300, default="")
#     # tagAddressPrefix                                    = models.CharField(max_length = 300, default="")
#     # tagAddressStreetName                                = models.CharField(max_length = 300, default="")
#     # tagAddressStreetType                                = models.CharField(max_length = 300, default="")
#     # tagAddressSuffix                                    = models.CharField(max_length = 300, default="")
#     # tagAddressHouseType                                 = models.CharField(max_length = 300, default="")
#     # tagAddressApartmentorSuiteNumber                    = models.CharField(max_length = 300, default="")
#     # tagAddressCity                                      = models.CharField(max_length = 300, default="")
#     # tagAddressState                                     = models.CharField(max_length = 300, default="")
#     # tagAddressZip5                                      = models.CharField(max_length = 300, default="")
#     # tagAddressZip4                                      = models.CharField(max_length = 300, default="")
#     # tagAddressDeliveryPointCode                         = models.CharField(max_length = 300, default="")
#     # tagAddressCarrierRoute                              = models.CharField(max_length = 300, default="")
#     # tagAddressCountyFIPS                                = models.CharField(max_length = 300, default="")
#     # tagAddressUSPSAddressType                           = models.CharField(max_length = 300, default="")
#     # tagAddressDeliveryValidation                        = models.CharField(max_length = 300, default="")
#     # tagAddressDeliverable                               = models.CharField(max_length = 300, default="")
#     # tagAddressLastValidationDate                        = models.CharField(max_length = 300, default="")
#     # tagAddressZip4TypeCode                              = models.CharField(max_length = 300, default="")
#     # tagAlternatePhoneNumbersAlternate1Number            = models.CharField(max_length = 300, default="")
#     # tagAlternatePhoneNumbersAlternate1DID               = models.CharField(max_length = 300, default="")
#     # tagAlternatePhoneNumbersAlternate1LocationType      = models.CharField(max_length = 300, default="")
#     # tagAlternatePhoneNumbersAlternate1RecordFound       = models.CharField(max_length = 300, default="")
#     # tagAlternatePhoneNumbersAlternate1RecordUpdated     = models.CharField(max_length = 300, default="")
#     # Alternate1Telco                                     = models.CharField(max_length = 300, default="")
#     # Alternate1Confidence                                = models.CharField(max_length = 300, default="")
#     # Alternate1DirectoryAssistance                       = models.CharField(max_length = 300, default="")
#     # Alternate2Number                                    = models.CharField(max_length = 300, default="")
#     # Alternate2Typ                                       = models.CharField(max_length = 300, default="")
#     # Alternate2DI                                        = models.CharField(max_length = 300, default="")
#     # Alternate2LocationType                              = models.CharField(max_length = 300, default="")
#     # Alternate2RecordFound                               = models.CharField(max_length = 300, default="")
#     # Alternate2RecordUpdated                             = models.CharField(max_length = 300, default="")
#     # Alternate2Telco                                     = models.CharField(max_length = 300, default="")
#     # Alternate2Confidence                                = models.CharField(max_length = 300, default="")
#     # Alternate2DirectoryAssistance                       = models.CharField(max_length = 300, default="")
#     # Alternate3Number                                    = models.CharField(max_length = 300, default="")
#     # Alternate3Type                                      = models.CharField(max_length = 300, default="")
#     # Alternate3DID                                       = models.CharField(max_length = 300, default="")
#     # Alternate3LocationType                              = models.CharField(max_length = 300, default="")
#     # Alternate3RecordFound                               = models.CharField(max_length = 300, default="")
#     # Alternate3RecordUpdated                             = models.CharField(max_length = 300, default="")
#     # Alternate3Telco                                     = models.CharField(max_length = 300, default="")
#     # Alternate3Confidence                                = models.CharField(max_length = 300, default="")
#     # Alternate3DirectoryAssistance                       = models.CharField(max_length = 300, default="")
#     # Email1Address                                       = models.CharField(max_length = 300, default="")
#     # Email1Suppression                                   = models.CharField(max_length = 300, default="")
#     # Email1Category                                      = models.CharField(max_length = 300, default="")
#     # Email1SHA2Hash                                      = models.CharField(max_length = 300, default="")
#     # Email1SHA1Hash                                      = models.CharField(max_length = 300, default="")
#     # Email1MD5Hash                                       = models.CharField(max_length = 300, default="")
#     # Email2Address                                       = models.CharField(max_length = 300, default="")
#     # Email2Suppression                                   = models.CharField(max_length = 300, default="")
#     # Email2Category                                      = models.CharField(max_length = 300, default="")
#     # Email2Sha2Hash                                      = models.CharField(max_length = 300, default="")
#     # Email2Sha1Hash                                      = models.CharField(max_length = 300, default="")
#     # Email2MD5Hash                                       = models.CharField(max_length = 300, default="")
#     # Email3Address                                       = models.CharField(max_length = 300, default="")
#     # Email3Suppression                                   = models.CharField(max_length = 300, default="")
#     # Email3Category                                      = models.CharField(max_length = 300, default="")
#     # Email3Sha2Hash                                      = models.CharField(max_length = 300, default="")
#     # Email3Sha1Hash                                      = models.CharField(max_length = 300, default="")
#     # Email3MD5Hash                                       = models.CharField(max_length = 300, default="")
#     # DemographicsGender                                  = models.CharField(max_length = 300, default="")
#     # DemographicsAge                                     = models.CharField(max_length = 300, default="")
#     # DemographicsRentorOwn                               = models.CharField(max_length = 300, default="")
#     # DemographicsSingleorMarried                         = models.CharField(max_length = 300, default="")
#     # DemographicsSingleParent                            = models.CharField(max_length = 300, default="")
#     # DemographicsSeniorCitizeninHome                     = models.CharField(max_length = 300, default="")
#     # DemographicsEducationLevel                          = models.CharField(max_length = 300, default="")
#     # tagDemographicsEthnicity                            = models.CharField(max_length = 300, default="")
#     # DemographicsChildreninHome                          = models.CharField(max_length = 300, default="")
#     # DemographicsChildrensAge                            = models.CharField(max_length = 300, default="")
#     # DemographicsNumberofChildren                        = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageBlack                         = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageWhite                         = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageHispanic                      = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageAsian                         = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageEnglishSpeaking               = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageSpanishSpeaking               = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageAsianSpeaking                 = models.CharField(max_length = 300, default="")
#     # DemographicsRespondstoDirectMail                    = models.CharField(max_length = 300, default="")
#     # DemographicsMedianYearsofSchool                     = models.CharField(max_length = 300, default="")
#     # DemographicsMedianHouseValue                        = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageAutomobileOwner               = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageWhiteCollar                   = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageBlueCollar                    = models.CharField(max_length = 300, default="")
#     # DemographicsPercentageOtherOccupation               = models.CharField(max_length = 300, default="")
#     # DemographicsLengthofResidence                       = models.CharField(max_length = 300, default="")
#     # DemographicsDwellingType                            = models.CharField(max_length = 300, default="")
#     # DemographicsHomeMarketValue                         = models.CharField(max_length = 300, default="")
#     # DemographicsDeceased                                = models.CharField(max_length = 300, default="")
#     # DemographicsVeteraninHome                           = models.CharField(max_length = 300, default="")
#     # DemographicsVeteranDisabled                         = models.CharField(max_length = 300, default="")
#     # FinancialInvestmentInterest                         = models.CharField(max_length = 300, default="")
#     # FinancialCreditCardUser                             = models.CharField(max_length = 300, default="")
#     # FinancialEstimatedNetWorth                          = models.CharField(max_length = 300, default="")
#     # FinancialEstimatedHouseholdIncome                   = models.CharField(max_length = 300, default="")
#     # FinancialEstimatedPurchasingPower                   = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsCharityDonor                      = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsValueShopper                      = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsWomensApparelBuyer                = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsMensApparelBuyer                  = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsParentingandChildren              = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsPets                              = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsBookBuyer                         = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsAvidReader                        = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsHiTechDevices                     = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsArts                              = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsCollectibles                      = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsHomeandGarden                     = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsHomeImprovementsorDIY             = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsFoodWineandCooking                = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsGamblingandSweepstakes            = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsTravel                            = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsFitness                           = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsSelfImprovement                   = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsAutomotive                        = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsSports                            = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsOutdoors                          = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsBoating                           = models.CharField(max_length = 300, default="")
#     # LifestyleInterestsMotorcycling                      = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1Make                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1Model                             = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1Year                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1Class                             = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1FuelType                          = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1ManufacturingCode                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1StyleCode                         = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1Mileage                           = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1OdometerCheckDate                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle1VIN                               = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2Make                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2Model                             = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2Year                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2Class                             = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2FuelType                          = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2ManufacturingCode                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2StyleCode                         = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2Mileage                           = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2OdometerCheckDate                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle2VIN                               = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3Make                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3Model                             = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3Year                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3Class                             = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3FuelType                          = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3ManufacturingCode                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3StyleCode                         = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3Mileage                           = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3OdometerCheckDate                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle3VIN                               = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4Make                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4Year                              = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4Class                             = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4FuelType                          = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4ManufacturingCode                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4StyleCode                         = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4Mileage                           = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4OdometerCheckDate                 = models.CharField(max_length = 300, default="")
#     # AutomotiveVehicle4VIN                               = models.CharField(max_length = 300, default="")
#     # ScoringAddress                                      = models.CharField(max_length = 300, default="")
#     # ScoringPhone                                        = models.CharField(max_length = 300, default="")
#     # ScoringEmail                                        = models.CharField(max_length = 300, default="")
#     # ScoringName                                         = models.CharField(max_length = 300, default="")
#     # ScoringNametoPhone                                  = models.CharField(max_length = 300, default="")
#     # ScoringNametoEmail                                  = models.CharField(max_length = 300, default="")
#     # ScoringNametoAddress                                = models.CharField(max_length = 300, default="")
#     # ScoringAddresstoPhone                               = models.CharField(max_length = 300, default="")
#     # ScoringAddresstoEmail                               = models.CharField(max_length = 300, default="")
#     # ScoringPhonetoEmail                                 = models.CharField(max_length = 300, default="")
#     # ScoringPhone2                                       = models.CharField(max_length = 300, default="")
#     # ScoringNametoPhone2                                 = models.CharField(max_length = 300, default="")
#     # ScoringAddresstoPhone2                              = models.CharField(max_length = 300, default="")
#     # ScoringPhone2toEmail                                = models.CharField(max_length = 300, default="")
#     # ScoringPhoneConfidence                              = models.CharField(max_length = 300, default="")
#     # ScoringPhone2Confidence                             = models.CharField(max_length = 300, default="")
#     # ScoringValidIdentifiers                             = models.CharField(max_length = 300, default="")
#     # ScoringValidDataLinks                               = models.CharField(max_length = 300, default="")
#     # ScoringFraudRisk                                    = models.CharField(max_length = 300, default="")
#     # ScoringOverallValidation                            = models.CharField(max_length = 300, default="")
#     # ScoringOverallLinkage                               = models.CharField(max_length = 300, default="")
#     # ScoringOverallRisk                                  = models.CharField(max_length = 300, default="")
#     # ScoringOverallIdentityVerification                  = models.CharField(max_length = 300, default="")
#     # MortgageMortgageLoanType                            = models.CharField(max_length = 300, default="")
#     # MortgageOwnerType                                   = models.CharField(max_length = 300, default="")
#     # MortgageMortgageSellerCarryBack                     = models.CharField(max_length = 300, default="")
#     # MortgageMortgageTitleCompany                        = models.CharField(max_length = 300, default="")
#     # MortgageMortgageLoantoValueLTV                      = models.CharField(max_length = 300, default="")
#     # MortgageMortgageAmount                              = models.CharField(max_length = 300, default="")
#     # MortgageMortgageDate                                = models.CharField(max_length = 300, default="")
#     # MortgageMortgageType                                = models.CharField(max_length = 300, default="")
#     # MortgageMortgageDeedType                            = models.CharField(max_length = 300, default="")
#     # MortgageMortgageTerm                                = models.CharField(max_length = 300, default="")
#     # MortgageMortgageDueDate                             = models.CharField(max_length = 300, default="")
#     # MortgageMortgageAmountAssumed                       = models.CharField(max_length = 300, default="")
#     # MortgageMortgageLenderName                          = models.CharField(max_length = 300, default="")
#     # MortgageMortgageRefiType                            = models.CharField(max_length = 300, default="")
#     # MortgageMortgageEquityinProperty                    = models.CharField(max_length = 300, default="")
#     # MortgageMortgageInterestRate                        = models.CharField(max_length = 300, default="")
#     # MortgageMortgageInterestRateType                    = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2Amount                             = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2Date                               = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2Type                               = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2DeedType                           = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2Term                               = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2DueDate                            = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2AssumptionAmount                   = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2LenderName                         = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2RefiType                           = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2EquityinProperty                   = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2InterestRate                       = models.CharField(max_length = 300, default="")
#     # MortgageMortgage2InterestRateType                   = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3Amount                             = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3Date                               = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3Type                               = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3DeedType                           = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3Term                               = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3DueDate                            = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3AssumptionAmount                   = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3LenderName                         = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3RefiType                           = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3EquityinProperty                   = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3InterestRate                       = models.CharField(max_length = 300, default="")
#     # MortgageMortgage3InterestRateType                   = models.CharField(max_length = 300, default="")
#     # PropertyLocationCountyFIPSCode                      = models.CharField(max_length = 300, default="")
#     # PropertyLocationCensusTract                         = models.CharField(max_length = 300, default="")
#     # PropertyLocationMunicipality                        = models.CharField(max_length = 300, default="")
#     # PropertyLocationTownship                            = models.CharField(max_length = 300, default="")
#     # PropertyLocationSubdivision                         = models.CharField(max_length = 300, default="")
#     # PropertyLocationZoning                              = models.CharField(max_length = 300, default="")
#     # PropertyLocationRange                               = models.CharField(max_length = 300, default="")
#     # PropertyLocationSection                             = models.CharField(max_length = 300, default="")
#     # PropertyLocationLatitude                            = models.CharField(max_length = 300, default="")
#     # PropertyLocationLongitude                           = models.CharField(max_length = 300, default="")
#     # PropertyLocationLandUseCode                         = models.CharField(max_length = 300, default="")
#     # PropertyLocationAssessorsParcelNumber               = models.CharField(max_length = 300, default="")
#     # PropertyLocationAssessorsSequenceNumber             = models.CharField(max_length = 300, default="")
#     # PropertyInformationOwnerOccupancy                   = models.CharField(max_length = 300, default="")
#     # PropertyInformationPropertyDataSource               = models.CharField(max_length = 300, default="")
#     # PropertyInformationPropertyOwnerEntity              = models.CharField(max_length = 300, default="")
#     # PropertyInformationResidentialBasedZipCode          = models.CharField(max_length = 300, default="")
#     # PropertyInformationPropertyType                     = models.CharField(max_length = 300, default="")
#     # PropertyInformationMobileHome                       = models.CharField(max_length = 300, default="")
#     # PropertyInformationNumberofBuildings                = models.CharField(max_length = 300, default="")
#     # PropertyInformationBuildingStyle                    = models.CharField(max_length = 300, default="")
#     # PropertyInformationNumberofStoriesCode              = models.CharField(max_length = 300, default="")
#     # PropertyInformationNumberofStories                  = models.CharField(max_length = 300, default="")
#     # PropertyInformationUnitNumber                       = models.CharField(max_length = 300, default="")
#     # PropertyInformationBuildingConstructionQuality      = models.CharField(max_length = 300, default="")
#     # PropertyInformationBuildingTypeCode                 = models.CharField(max_length = 300, default="")
#     # PropertyInformationBuildingImprovementType          = models.CharField(max_length = 300, default="")
#     # PropertyInformationPropertyCondition                = models.CharField(max_length = 300, default="")
#     # PropertyInformationConstructionType                 = models.CharField(max_length = 300, default="")
#     # PropertyInformationExteriorWallsType                = models.CharField(max_length = 300, default="")
#     # PropertyInformationTotalLandImprovementValue        = models.CharField(max_length = 300, default="")
#     # PropertyInformationPropertyValueType                = models.CharField(max_length = 300, default="")
#     # PropertyInformationLandValue                        = models.CharField(max_length = 300, default="")
#     # PropertyInformationLandValueIndicator               = models.CharField(max_length = 300, default="")
#     # PropertyInformationImprovementValue                 = models.CharField(max_length = 300, default="")
#     # PropertyInformationImprovementValueIndicator        = models.CharField(max_length = 300, default="")
#     # PropertyInformationTotalAssessedValue               = models.CharField(max_length = 300, default="")
#     # PropertyInformationAssessedLandValue                = models.CharField(max_length = 300, default="")
#     # PropertyInformationAssessedImprovementValue         = models.CharField(max_length = 300, default="")
#     # PropertyInformationTotalMarketValue                 = models.CharField(max_length = 300, default="")
#     # PropertyInformationMarketLandValues                 = models.CharField(max_length = 300, default="")
#     # PropertyInformationMarketImprovementValues          = models.CharField(max_length = 300, default="")
#     # PropertyInformationTotalAppraisedValue              = models.CharField(max_length = 300, default="")
#     # PropertyInformationAppraisedLandValue               = models.CharField(max_length = 300, default="")
#     # PropertyInformationAppraisedImprovementValue        = models.CharField(max_length = 300, default="")
#     # PropertyConstructionPropertyView                    = models.CharField(max_length = 300, default="")
#     # PropertyConstructionLocationAssociatedAspects       = models.CharField(max_length = 300, default="")
#     # PropertyConstructionFrontLinearFeet                 = models.CharField(max_length = 300, default="")
#     # PropertyConstructionLinearFeetBetween               = models.CharField(max_length = 300, default="")
#     # PropertyConstructionTotalAcreage                    = models.CharField(max_length = 300, default="")
#     # PropertyConstructionTotalSquareFeet                 = models.CharField(max_length = 300, default="")
#     # PropertyConstructionYearBuilt                       = models.CharField(max_length = 300, default="")
#     # PropertyConstructionEffectiveYearBuilt              = models.CharField(max_length = 300, default="")
#     # PropertyConstructionBuildingSquareFootage           = models.CharField(max_length = 300, default="")
#     # PropertyConstructionSquareFootageType               = models.CharField(max_length = 300, default="")
#     # PropertyConstructionBuildingSquareFeet              = models.CharField(max_length = 300, default="")
#     # PropertyConstructionLivingSquareFootage             = models.CharField(max_length = 300, default="")
#     # PropertyConstructionSquareFootageFront              = models.CharField(max_length = 300, default="")
#     # PropertyConstructionBuildingSquareFootageFront      = models.CharField(max_length = 300, default="")
#     # PropertyConstructionSquareFootageforImprovements    = models.CharField(max_length = 300, default="")
#     # PropertyConstructionBasementSquareFootage           = models.CharField(max_length = 300, default="")
#     # PropertyConstructionParkingSquareFootage            = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofRooms                   = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofBedrooms                = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofBathrooms               = models.CharField(max_length = 300, default="")
#     # PropertyConstructionTotalBathrooms                  = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofFullBaths               = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofHalfBaths               = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofQuarterBaths            = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofThreeQuarterBaths       = models.CharField(max_length = 300, default="")
#     # PropertyConstructionTotalBathroomFixtures           = models.CharField(max_length = 300, default="")
#     # PropertyConstructionAirConditioningType             = models.CharField(max_length = 300, default="")
#     # PropertyConstructionBasementType                    = models.CharField(max_length = 300, default="")
#     # PropertyConstructionFireplace                       = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofFirePlaces              = models.CharField(max_length = 300, default="")
#     # PropertyConstructionFireplaceType                   = models.CharField(max_length = 300, default="")
#     # PropertyConstructionFoundationType                  = models.CharField(max_length = 300, default="")
#     # PropertyConstructionFloorConstructionType           = models.CharField(max_length = 300, default="")
#     # PropertyConstructionRoofFramingType                 = models.CharField(max_length = 300, default="")
#     # PropertyConstructionGarageType                      = models.CharField(max_length = 300, default="")
#     # PropertyConstructionMethodofHeating                 = models.CharField(max_length = 300, default="")
#     # PropertyConstructionNumberofParkingSpaces           = models.CharField(max_length = 300, default="")
#     # PropertyConstructionParkingType                     = models.CharField(max_length = 300, default="")
#     # PropertyConstructionPool                            = models.CharField(max_length = 300, default="")
#     # PropertyConstructionPoolType                        = models.CharField(max_length = 300, default="")
#     # PropertyConstructionRoofCovering                    = models.CharField(max_length = 300, default="")
#     # PropertyConstructionRoofType                        = models.CharField(max_length = 300, default="")
#     # PropertyConstructionElectricityType                 = models.CharField(max_length = 300, default="")
#     # PropertyConstructionHeatingFuelType                 = models.CharField(max_length = 300, default="")
#     # PropertyConstruction_SewerType                      = models.CharField(max_length = 300, default="")
#     # PropertyConstructionWaterSupplyType                 = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentHomesteadQualified            = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentTaxAmount                     = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentTaxYear                       = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentSaleYear                      = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentDeedType                      = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentRecordingDate                 = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentSellersName                   = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentSaleDate                      = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentSaleAmount                    = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentSaleCode                      = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentParcelSaleCode                = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentNumberofParcels               = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentLastAssessmentYear            = models.CharField(max_length = 300, default="")
#     # PropertyDeedAssessmentSaleType                      = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorRecordedSaleDate              = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorCompletedSaleDate             = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriceofSale                        = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorSaleType                      = models.CharField(max_length = 300, default="")
#     # PropertyPriorSaleParcelType                         = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorDeedCode                      = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorSaleYearRecorded              = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorDeedType                      = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorSaleTransactionCode           = models.CharField(max_length = 300, default="")
#     # PropertyPriorSalePriorSaleMortgageAmount            = models.CharField(max_length = 300, default="")

#     def __str__(self):
#         return str(self.id)

#     class Meta:
#         verbose_name = ("Silent data")
#         verbose_name_plural = ("Silent data")  
