# Generated by Django 4.1.4 on 2022-12-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='total_debt_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
