# Generated by Django 4.1.4 on 2022-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_offers',
            name='image',
            field=models.ImageField(default='default.png', upload_to='offers'),
        ),
    ]
