# Generated by Django 4.1.4 on 2022-12-28 17:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='terms_and_privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_privacy', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
