# Generated by Django 4.1.4 on 2022-12-28 18:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_privacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='terms_and_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_condition', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='terms_and_privacy',
            new_name='privacy_policy',
        ),
    ]
